package com.moneylion.fvoon.clashofinserts;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum FundOptionTypes {
    MONEYLION_COREPRO_ACCOUNT("MONEYLION_COREPRO_ACCOUNT", "MONEYLION_COREPRO_ACCOUNT"),
    MONEYLION_COREPRO_NEGATIVE_BAL_ACCOUNT("MONEYLION_COREPRO_NEGATIVE_BAL_ACCOUNT", "ML_PROGRAM_RESERVE_NEGATIVE_BALANCE"),
    MONEYLION_COREPRO_ACCOUNT_ESCROW("MONEYLION_COREPRO_ACCOUNT_ESCROW", "ML_PROGRAM_RESERVE_FUNDING_ESCROW"),
    MONEYLION_COREPRO_ATM_FEE_ACCOUNT("MONEYLION_COREPRO_ATM_FEE_ACCOUNT", "ML_PROGRAM_RESERVE_ATM_FEES"),
    MONEYLION_COREPRO_INSTACASH_ACCOUNT("MONEYLION_COREPRO_INSTACASH_ACCOUNT", "ML_PROGRAM_RESERVE_INSTACASH"),
    MONEYLION_COREPRO_INSTACASH_FEES_ACCOUNT("MONEYLION_COREPRO_INSTACASH_FEES_ACCOUNT", "ML_PROGRAM_RESERVE_INSTACASH_FEES"),
    MONEYLION_CLEARING_ACCOUNT("MONEYLION_CLEARING_ACCOUNT", "ML_PROGRAM_CLEARING_ACCOUNT"),
    MONEYLION_PUSH_TO_DEBIT_ACCOUNT("MONEYLION_PUSH_TO_DEBIT_ACCOUNT", "MONEYLION_WELLS_ACCOUNT"),
    MONEYLION_COREPRO_LOAN_ACCOUNT("MONEYLION_COREPRO_LOAN_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING_LOAN"),
    MONEYLION_COREPRO_INVESTMENT_ACCOUNT("MONEYLION_COREPRO_INVESTMENT_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING_INVESTMENT"),
    DDA_CHECKING("DDA_CHECKING", "MoneyLion Checking"),
    DDA_FIRST_LINKED("DDA_FIRST_LINKED", "MoneyLion External Linked Account"),
    ML_INVESTMENT("ML_INVESTMENT", "MoneyLion Investment"),
    MONEYLION_LOAN_OWNER_ACCOUNT("MONEYLION_LOAN_OWNER_ACCOUNT", "MoneyLion Loan Owner Account"),
    @Deprecated MONEYLION_DEBIT_CARD("MONEYLION_DEBIT_CARD", "MoneyLion Debit Card"), // moneylion debit card identifier is now in FundDetails.isMoneylionCard
    DEBIT_CARD("DEBIT_CARD", "Debit Card"),
    CREDIT_CARD("CREDIT_CARD", "Credit Card"),
    ACH("ACH", "ACH"),
    CRYPTO("CRYPTO", "MoneyLion Crypto"),
    RCC("RCC", "RCC"),
    ML_INVESTMENT_ESCROW("ML_INVESTMENT_ESCROW", "MoneyLion Escrow"),
    MONEYLION_PRE_FUNDING_ACCOUNT("MONEYLION_PRE_FUNDING_ACCOUNT", "MONEYLION_PRE_FUNDING_ACCOUNT"),
    MONEYLION_PAYMENT_PROCESSOR_ACCOUNT("MONEYLION_PAYMENT_PROCESSOR_ACCOUNT", "MONEYLION_PAYMENT_PROCESSOR_ACCOUNT"),
    DEMAND_DEPOSIT_ACCOUNT("DEMAND_DEPOSIT_ACCOUNT", "RoarMoney"),
    MONEYLION_GALILEO_INSTACASH_ACCOUNT("MONEYLION_GALILEO_INSTACASH_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_LOAN_ACCOUNT("MONEYLION_GALILEO_LOAN_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_DDA_FUNDING_ACCOUNT("MONEYLION_GALILEO_DDA_FUNDING_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_ESCROW_ACCOUNT("MONEYLION_GALILEO_ESCROW_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_INVESTMENT_ACCOUNT("MONEYLION_GALILEO_INVESTMENT_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_SUBSCRIPTION_ACCOUNT("MONEYLION_GALILEO_SUBSCRIPTION_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_NEGATIVE_BAL_ACCOUNT("MONEYLION_GALILEO_NEGATIVE_BAL_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_PROMOTION_ACCOUNT("MONEYLION_GALILEO_PROMOTION_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_CRYPTO_ACCOUNT("MONEYLION_GALILEO_CRYPTO_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_ROUND_UP_INVESTMENT_ACCOUNT("MONEYLION_GALILEO_ROUND_UP_INVESTMENT_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_ROUND_UP_CRYPTO_ACCOUNT("MONEYLION_GALILEO_ROUND_UP_CRYPTO_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    MONEYLION_GALILEO_OVERTIME_ACCOUNT("MONEYLION_GALILEO_OVERTIME_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    TOKENIZED_PUSH_TO_DEBIT_ACCOUNT("TOKENIZED_PUSH_TO_DEBIT_ACCOUNT", "TOKENIZED_PUSH_TO_DEBIT_ACCOUNT"),
    MONEYLION_CHARGE_CARD_ACCOUNT("MONEYLION_CHARGE_CARD_ACCOUNT", "MONEYLION_CHARGE_CARD_ACCOUNT"),
    MONEYLION_GALILEO_INTEREST_PROMOTION_ACCOUNT("MONEYLION_GALILEO_INTEREST_PROMOTION_ACCOUNT", "ML_PROGRAM_RESERVE_FUNDING"),
    ML_ACTIVE_INVESTMENT("ML_ACTIVE_INVESTMENT", "MoneyLion Active Investment"),
    MONEYLION_REWARDS_INVESTMENT_ACCOUNT("MONEYLION_REWARDS_INVESTMENT_ACCOUNT", "MONEYLION_REWARDS_INVESTMENT_ACCOUNT"),
    MONEYLION_GALILEO_DDA_INSTANT_CASH_OUT_ACCOUNT("MONEYLION_GALILEO_DDA_INSTANT_CASH_OUT_ACCOUNT", "MONEYLION_GALILEO_DDA_INSTANT_CASH_OUT_ACCOUNT"),
    MONEYLION_GALILEO_ACTIVE_INVESTMENT_ACCOUNT("MONEYLION_GALILEO_ACTIVE_INVESTMENT_ACCOUNT", "MONEYLION_GALILEO_ACTIVE_INVESTMENT_ACCOUNT"),
    MONEYLION_GALILEO_TURBO_FEE_REBATE_ACCOUNT("MONEYLION_GALILEO_TURBO_FEE_REBATE_ACCOUNT", "MONEYLION_GALILEO_TURBO_FEE_REBATE_ACCOUNT"),
    APPLE_PAY("APPLE_PAY", "APPLE_PAY"),
    GOOGLE_PAY("GOOGLE_PAY", "GOOGLE_PAY"),
    ;

    private final String value;

    private final String name;

    @Override
    public String toString() {
        return this.value;
    }

    public String getDisplayName() {
        return switch (this) {
            case ML_INVESTMENT -> "Managed Investing account";
            case ML_ACTIVE_INVESTMENT -> "Active Investing account";
            case DEBIT_CARD -> DEBIT_CARD.getName();
            case DEMAND_DEPOSIT_ACCOUNT -> "RoarMoney account";
            case ACH -> ACH.getName();
            case APPLE_PAY -> "Apple Pay";
            case GOOGLE_PAY -> "Google Pay";
            default -> "";
        };
    }
}
